### ISSUE TITLE
google wifi web dashboard

### ISSUE THREAD

**Issue by JamesHawkinss** [olssonm/google-wifi-api#11]
Hi there,

Using some of the API endpoints available for Google Wifi, I have made a web dashboard as an alternative for the mobile app. It is still in progress. but it is looking alright at the moment. It is based heavily from the original design and functionality of the app.

Site: [wifi.squeezebox.dev](https://wifi.squeezebox.dev)
Code: [github.com/JamesHawkinss/google-wifi-dashboard](https://github.com/JamesHawkinss/google-wifi-dashboard)

Here are some images of it so far:
 - Overview page: https://sxu.squeezebox.dev/eb8a4/mEpALuYU59.png/raw
 - Network page, feat realtime metrics: https://sxu.squeezebox.dev/eb8a4/LeMApehI00.png/raw
 - Devices page: https://sxu.squeezebox.dev/eb8a4/wUmeJOwo40.png/raw

Thought you might find it interesting.

**Comment by olssonm** [comment]
Thanks for the tip, and it does look cool! But not really an issue relevant to this repository. 

I'll check it out and perhaps add a link to the project later on.
